# Generated by Django 5.1.2 on 2025-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofileapp', '0003_remove_order_user_useraddress_delete_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='name',
            field=models.CharField(default='Unnamed User', max_length=25),
        ),
    ]
