# Generated by Django 5.1.2 on 2025-04-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofileapp', '0004_useraddress_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
