# Generated by Django 5.1.2 on 2025-04-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofileapp', '0005_alter_useraddress_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
