# Generated by Django 5.1.2 on 2024-10-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accountsapp', '0002_myuser_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
