# Generated by Django 5.1.2 on 2024-12-07 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categoryapp', '0002_alter_category_options_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='categoryslug',
        ),
    ]
