# Generated by Django 5.1.2 on 2024-12-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Categoryapp', '0003_rename_slug_category_categoryslug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categoryslug',
            new_name='slug',
        ),
    ]
