# Generated by Django 5.1.2 on 2024-10-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
