# Generated by Django 5.1.2 on 2024-12-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productapp', '0005_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
