# Generated by Django 5.1.2 on 2024-12-07 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_remove_cartitem_price_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
    ]
