# Generated by Django 5.1.2 on 2025-04-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_remove_order_shipping_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
